### ISSUE TITLE
Docker flavour cannot fetch data

### ISSUE THREAD

**Issue by thetechgeekster** [tborychowski/zakupnik3#68]
When using the Docker flavour of the app, data cannot be fetched and always shows the "Loading..." placeholder. When trying to add a category, the app crashes. 

![image](https://user-images.githubusercontent.com/38396429/89388881-4deac680-d70d-11ea-8a42-67d0077fb1e6.png)

**Comment by tborychowski** [comment]
🤔 
can you post your `docker-compose.yml` file (or docker command if you're using that)?

I'm guessing this is because of permissions?(e.g. docker user, which wants to create the db file, does not have permissions to do that, due to your host's permissions of the mounted volume).

could you try this out and see if it makes any difference?
1. create an empty file: `touch database.db` (or `sudo...` if needed)
2. change its permissions `sudo chmod 777 database.db`
3. restart docker container (`docker-compose down && docker-compose up -d`)

Alternatively, change the permissions of the folder where the mounted db file should be.
